### ISSUE TITLE
Support ads.txt

### ISSUE THREAD

**Issue by spekulatius** [YunYouJun/vuepress-plugin-google-adsense#3]
Hello @YunYouJun ,

is it possible to support the `ads.txt` Google requires? Not sure if and how you would do this.

Cheers,
Peter

**Comment by YunYouJun** [comment]
Yeah. Good idea. I will try it.

**Comment by spekulatius** [comment]
Awesome, thank you @YunYouJun

**Comment by YunYouJun** [comment]
In https://github.com/YunYouJun/vuepress-plugin-google-adsense/commit/ff1090c72e5691dbdaaf66f5b6ea9b1585359714, a new option called `adsTxt` is added.

For example:

```js
plugins: {
    "vuepress-plugin-google-adsense": {
      adClient: "ca-pub-2245427233262012",
      adsTxt: true,
    },
}
```

> https://support.google.com/adsense/answer/7532444

The following content will be generated in ads.txt.

```txt
google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0
```

`ad_client` is renamed `adClient`, `ad_client` is also compatible, will be deprecated in future.

Released in [v0.2.0](https://www.npmjs.com/package/vuepress-plugin-google-adsense).

**Comment by spekulatius** [comment]
Hello @YunYouJun 

Cool, I've tried it out! 

Works like a charm, thank you!

Cheers,
Peter

**Comment by YunYouJun** [comment]
Thanks.
